using RGR_Project;
Console.WriteLine("<< RGR >>");
//Truck t = new Truck();
//t.display();
//t.deliver();
//t.fillfuel();
Creator truckcreate = new TransportCreator();
Creator planecreate = new TransportCreator();
Creator shipcreate = new TransportCreator();
Transport truck = truckcreate.CreateTransport("truck");
Transport plane = planecreate.CreateTransport("plane");
Transport ship = shipcreate.CreateTransport("ship");
Transport ship1 = new GPS_navigator(ship);
ship1.display();
//truck.display();
//truck.deliver();
//truck.delivertime();
//Console.WriteLine(new string('*', 50));
//plane.display();
//plane.deliver();
//plane.delivertime();
//Console.WriteLine(new string('*', 50));
//ship.display();
//ship.deliver();
//ship.delivertime();

