using RGR_Project;
Console.WriteLine("<< RGR >>");
//Truck t = new Truck();
//t.display();
//t.deliver();
//t.fillfuel();
Delivery truckcreate = new RoadDelivery();
Delivery planecreate = new WindDelivery();
Delivery shipcreate = new SeaDelivery();
Transport truck = truckcreate.CreateTransport();
Transport plane = planecreate.CreateTransport();
Transport ship = shipcreate.CreateTransport();
truck.display();
truck.fillfuel();
truck.deliver();
truck.delivertime();
//Console.WriteLine(new string ('*', 50));
//plane.display();
//plane.fillfuel();
//plane.deliver();
//plane.delivertime();
//Console.WriteLine(new string('*', 50));
//ship.display();
//ship.fillfuel();
//ship.deliver();
//ship.delivertime();
truck.SetEngineUpdateBehaviour(new EngineUpdate());
truck.deliver();